import { generateText, gateway } from "ai";

import { env } from "~/env";
import { mapPool } from "~/server/util/pool";

/**
 * Contextual Retrieval (Anthropic's technique). A raw transcript chunk, ripped out of its
 * video, is often ambiguous on its own — "he said to double it" means nothing without knowing
 * what "it" is. Before embedding, we prepend a one-or-two-sentence blurb that situates the
 * chunk inside the whole transcript, so both the dense vector and the sparse `tsv` carry that
 * context. Reported effect: ~-49% retrieval failures vs. embedding the bare chunk.
 *
 * The blurb is generated by a cheap model, once per chunk, entirely offline during ingestion —
 * the query path never pays for it.
 */

const CONCURRENCY = 5;

/** The document goes first so it forms a shared prefix across every chunk of the same video —
 * the exact shape a provider prompt-cache rewards once we pin a cache-capable context model. */
function contextPrompt(documentText: string, chunkText: string): string {
  return `<document>
${documentText}
</document>

Here is a chunk taken from that document:
<chunk>
${chunkText}
</chunk>

Give a short, succinct context (1-2 sentences) that situates this chunk within the overall document, to improve search retrieval of the chunk. Name the specific topic, person, or idea the chunk's pronouns and references point to. Answer ONLY with the context, nothing else.`;
}

async function contextualizeOne(
  documentText: string,
  chunkText: string,
): Promise<string> {
  const { text } = await generateText({
    model: gateway(env.CONTEXT_MODEL),
    prompt: contextPrompt(documentText, chunkText),
  });
  return text.trim();
}

/**
 * Generate one context blurb per chunk, all situated against the same full transcript. Returns
 * a blurb per input chunk, in order — the pipeline prepends each to its chunk before embedding.
 */
export function contextualizeChunks(
  documentText: string,
  chunkTexts: string[],
): Promise<string[]> {
  return mapPool(chunkTexts, CONCURRENCY, (text) =>
    contextualizeOne(documentText, text),
  );
}
